### ISSUE TITLE
What non-standard libraries are used in the original ElMD implementation?

### ISSUE THREAD

**Issue by sgbaird** [CompRhys/EleMD#1]
Curious what is the motivation for this repo.

**Comment by CompRhys** [comment]
The original implementation on pypi was written in pure python which was about 5-10x slower than using `pot` (think the `numba` branch is likely comparable in speed but had issues getting it to work).
`pot` is what I mean by standard library

**Comment by CompRhys** [comment]
I also wanted to test using the `elemd` as a kernel function so wanted a signature f(A,B) rather than g(A).h(A) .

**Comment by sgbaird** [comment]
Gotcha. I also needed some speedup from the original implementation. I ended up implementing a CUDA/Numba version of Earth Mover's Distance and integrating that into a forked version of ElM2D. I like how simple the code is in EleMD - pretty straightforward. I've enjoyed looking through your various repos!

**Comment by sgbaird** [comment]
See `cuda_dist_matrix.py` for implementation and `ElM2D_.py` for usage. https://github.com/sparks-baird/mat_discover/tree/main/mat_discover/ElM2D
