### ISSUE TITLE
ModuleNotFoundError: No module named 'ot'

### ISSUE THREAD

**Issue by sgbaird** [CompRhys/EleMD#2]
After following the instructions in the README:
```python
(mat_discover_test) C:\Users\sterg\Documents\GitHub\scratch\EleMD>python
Python 3.9.7 | packaged by conda-forge | (default, Sep 
29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)] on win32Type "help", "copyright", "credits" or "license" for more information.
>>> import EleMD
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sterg\Documents\GitHub\scratch\EleMD\EleMD\__init__.py", line 1, in <module>
    from EleMD.elemd import EleMD
  File "C:\Users\sterg\Documents\GitHub\scratch\EleMD\EleMD\elemd.py", line 4, in <module>
    from ot import emd2
ModuleNotFoundError: No module named 'ot'
```
After checking the POT website:

> Note that due to a limitation of pip, cython and numpy need to be installed prior to installing POT. This can be done easily with
> 
> `pip install numpy cython`
> You can install the toolbox through PyPI with:
> 
> `pip install POT`

After this, I was able to import `ot`.

**Comment by CompRhys** [comment]
I just had the requirements split out in `requirements.txt` files but have now also added to `setup.py`, thanks for raising!
